# Generated by Django 2.1.15 on 2021-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Date',
            field=models.DateField(),
        ),
    ]
